module.exports = [{
  path: '/',
  component: require('../../pages/Signin/Signin.js').default
}, {
  path: '/signin',
  component: require('../../pages/Signin/Signin.js').default
}, {
  path: '/opportunities',
  component: require('../../pages/Opportunities/Opportunities').default
}, {
  path: '/opportunities/:id',
  component: require('../../pages/Opportunity/Opportunity.js').default
}, {
  path: '/partners',
  component: require('../../pages/Partners/Partners.js').default
}, {
  path: '/help',
  component: require('../../pages/Help/Help.js').default
}, {
  path: '/dashboard/:endpoint/search',
  component: require('../../pages/SearchPage/SearchPage.js').default,
  admin: true
}, {
  path: '/dashboard/:endpoint/add',
  component: require('../../pages/PostPage/PostPage.js').default,
  admin: true
}, {
  path: '/dashboard/:endpoint/edit/:id',
  component: require('../../pages/PutPage/PutPage.js').default,
  admin: true
}, {
  path: '/dashboard/:endpoint/view/:id',
  component: require('../../pages/ViewPage/ViewPage.js').default,
  admin: true
}, {
  component: require('../../pages/Page404/Page404.js').default
}];