module.exports = [{
  path: '/',
  component: require('../../pages/Signin/Signin.js').default
}, {
  path: '/signin',
  component: require('../../pages/Signin/Signin.js').default
}, {
  path: '/help',
  component: require('../../pages/Help/Help.js').default
}, {
  path: '/opportunities',
  component: require('../../pages/Opportunities/Opportunities').default,
  role: 'user'
}, {
  path: '/opportunities/view/:id',
  component: require('../../pages/Opportunities/ViewOpportunity/ViewOpportunity').default,
  role: 'user'
}, {
  path: '/opportunities/post',
  component: require('../../pages/Opportunities/PostOpportunity/PostOpportunity').default,
  role: 'user'
}, {
  path: '/opportunities/edit/:id',
  component: require('../../pages/Opportunities/PutOpportunity/PutOpportunity').default,
  role: 'user'
}, {
  path: '/partners',
  component: require('../../pages/Partners/Partners.js').default,
  role: 'user'
}, {
  path: '/partners/post',
  component: require('../../pages/Partners/PostPartner/PostPartner.js').default,
  role: 'user'
}, {
  path: '/partners/edit/:id',
  component: require('../../pages/Partners/PutPartner/PutPartner').default,
  role: 'user'
}, {
  path: '/dashboard/:endpoint/search',
  component: require('../../pages/SearchPage/SearchPage.js').default,
  role: 'admin'
}, {
  path: '/dashboard/:endpoint/add',
  component: require('../../pages/PostPage/PostPage.js').default,
  role: 'admin'
}, {
  path: '/dashboard/:endpoint/edit/:id',
  component: require('../../pages/PutPage/PutPage.js').default,
  role: 'admin'
}, {
  path: '/dashboard/:endpoint/view/:id',
  component: require('../../pages/ViewPage/ViewPage.js').default,
  role: 'admin'
}, {
  component: require('../../pages/Page404/Page404.js').default
}];