"""create partner and opportunity

Revision ID: 1b8ebca6acad
Revises: 7d30ce7b582b
Create Date: 2018-10-21 15:17:55.686013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8ebca6acad'
down_revision = '7d30ce7b582b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_id'), 'partner', ['id'], unique=False)
    op.create_index(op.f('ix_partner_name'), 'partner', ['name'], unique=True)
    op.create_table('opportunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('job_number', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(length=500), nullable=True),
    sa.Column('shift_hours', sa.Float(), nullable=True),
    sa.Column('commitment_length', sa.Float(precision=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('training_time_required', sa.Integer(), nullable=True),
    sa.Column('volunteers_needed', sa.Integer(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_number')
    )
    op.create_index(op.f('ix_opportunity_id'), 'opportunity', ['id'], unique=False)
    op.create_index(op.f('ix_opportunity_name'), 'opportunity', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_name'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_id'), table_name='opportunity')
    op.drop_table('opportunity')
    op.drop_index(op.f('ix_partner_name'), table_name='partner')
    op.drop_index(op.f('ix_partner_id'), table_name='partner')
    op.drop_table('partner')
    # ### end Alembic commands ###
