"""tags categories

Revision ID: 28c6d0d63b38
Revises: 30a7f0719cb0
Create Date: 2019-03-04 19:58:05.809396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c6d0d63b38'
down_revision = '30a7f0719cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_category_id'), 'tag_category', ['id'], unique=False)
    op.create_index(op.f('ix_tag_category_name'), 'tag_category', ['name'], unique=True)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('tag_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_category_id'], ['tag_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_table('tags',
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('tags_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_tag_category_name'), table_name='tag_category')
    op.drop_index(op.f('ix_tag_category_id'), table_name='tag_category')
    op.drop_table('tag_category')
    # ### end Alembic commands ###
