"""empty message

Revision ID: 2f61a688063d
Revises: fe5f1a41b8a1
Create Date: 2019-08-26 15:59:49.979664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f61a688063d'
down_revision = 'fe5f1a41b8a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("opportunity") as batch_op:
        batch_op.alter_column('tags_string', type_=sa.String(length=400),
                              existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("opportunity") as batch_op:
        batch_op.alter_column('tags_string', type_=sa.String(length=200),
                              existing_nullable=True)
    # ### end Alembic commands ###
