"""Rename password field to password_hash

Revision ID: 2f738cbdac92
Revises: c82e8bdebce2
Create Date: 2018-10-14 23:09:05.588310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f738cbdac92'
down_revision = 'c82e8bdebce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as bop:
        bop.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), nullable=True))
        bop.drop_column('password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as bop:
        bop.add_column(sa.Column('password', sa.VARCHAR(length=255), nullable=True))
        bop.drop_column('password_hash')
    # ### end Alembic commands ###
