"""empty message

Revision ID: 38aa8ac3902e
Revises: 911f36815f83
Create Date: 2019-05-05 10:34:40.692805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38aa8ac3902e'
down_revision = '911f36815f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("opportunity") as batch_op:
        batch_op.drop_column('job_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("opportunity") as batch_op:
        batch_op.add_column(sa.Column('job_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('opportunity_job_number_key', ['job_number'])
    # ### end Alembic commands ###
