"""empty message

Revision ID: 71d7f125f39a
Revises: 2f61a688063d
Create Date: 2019-08-26 16:15:13.060125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d7f125f39a'
down_revision = '2f61a688063d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("opportunity") as batch_op:
        batch_op.alter_column('tags_string', type_=sa.String(length=2000),
                              existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("opportunity") as batch_op:
        batch_op.alter_column('tags_string', type_=sa.String(length=400),
                              existing_nullable=True)
    # ### end Alembic commands ###
