"""empty message

Revision ID: 911f36815f83
Revises: dff188188029
Create Date: 2019-05-04 11:50:52.087280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911f36815f83'
down_revision = 'dff188188029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("opportunity") as batch_op:
        batch_op.add_column(sa.Column('training_time_hours', sa.Integer(), nullable=True))
        batch_op.drop_column('training_time_required')
    with op.batch_alter_table("opportunity") as batch_op:
        batch_op.add_column(sa.Column('commitment_length_months', sa.Integer(), nullable=True))
        batch_op.drop_column('commitment_length')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("opportunity") as batch_op:
        batch_op.add_column(sa.Column('training_time_required', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('training_time_hours')
    with op.batch_alter_table("opportunity") as batch_op:
        batch_op.add_column(sa.Column('commitment_length', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('commitment_length_months')
    # ### end Alembic commands ###
