"""empty message

Revision ID: a095c5d1eb8d
Revises: c0f3de3fdbe0
Create Date: 2018-10-25 19:22:05.318275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a095c5d1eb8d'
down_revision = 'c0f3de3fdbe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_frequency_name'), 'frequency', ['name'], unique=True)
    op.create_index(op.f('ix_passion_name'), 'passion', ['name'], unique=True)
    op.create_index(op.f('ix_skill_name'), 'skill', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_name'), table_name='skill')
    op.drop_index(op.f('ix_passion_name'), table_name='passion')
    op.drop_index(op.f('ix_frequency_name'), table_name='frequency')
    # ### end Alembic commands ###
