"""empty message

Revision ID: bcdfd59345cc
Revises:
Create Date: 2019-03-20 18:15:34.208187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcdfd59345cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frequency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frequency_id'), 'frequency', ['id'], unique=False)
    op.create_index(op.f('ix_frequency_name'), 'frequency', ['name'], unique=True)
    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_id'), 'partner', ['id'], unique=False)
    op.create_index(op.f('ix_partner_name'), 'partner', ['name'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_category_id'), 'tag_category', ['id'], unique=False)
    op.create_index(op.f('ix_tag_category_name'), 'tag_category', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_table('opportunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('job_number', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('shift_hours', sa.Float(), nullable=True),
    sa.Column('commitment_length', sa.Float(precision=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('training_time_required', sa.Integer(), nullable=True),
    sa.Column('volunteers_needed', sa.Integer(), nullable=True),
    sa.Column('location_street', sa.String(length=100), nullable=True),
    sa.Column('location_city', sa.String(length=50), nullable=True),
    sa.Column('location_zip', sa.String(length=10), nullable=True),
    sa.Column('tags_string', sa.String(length=200), nullable=True),
    sa.Column('partner_string', sa.String(length=100), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('frequency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['frequency_id'], ['frequency.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_number')
    )
    op.create_index(op.f('ix_opportunity_id'), 'opportunity', ['id'], unique=False)
    op.create_index(op.f('ix_opportunity_name'), 'opportunity', ['name'], unique=True)
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('tag_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_category_id'], ['tag_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_table('tags',
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('tags_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_table('roles_users')
    op.drop_index(op.f('ix_opportunity_name'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_id'), table_name='opportunity')
    op.drop_table('opportunity')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tag_category_name'), table_name='tag_category')
    op.drop_index(op.f('ix_tag_category_id'), table_name='tag_category')
    op.drop_table('tag_category')
    op.drop_table('role')
    op.drop_index(op.f('ix_partner_name'), table_name='partner')
    op.drop_index(op.f('ix_partner_id'), table_name='partner')
    op.drop_table('partner')
    op.drop_index(op.f('ix_frequency_name'), table_name='frequency')
    op.drop_index(op.f('ix_frequency_id'), table_name='frequency')
    op.drop_table('frequency')
    # ### end Alembic commands ###
