"""skill model and opportunity relationship

Revision ID: be6d46598b14
Revises: e2263aed3789
Create Date: 2018-10-21 20:40:57.598754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6d46598b14'
down_revision = 'e2263aed3789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_id'), 'skill', ['id'], unique=False)
    op.create_table('skills',
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('skills_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['skills_id'], ['skill.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    op.drop_index(op.f('ix_skill_id'), table_name='skill')
    op.drop_table('skill')
    # ### end Alembic commands ###
