"""frequency model and opportunity relationship

Revision ID: c0f3de3fdbe0
Revises: be6d46598b14
Create Date: 2018-10-21 21:11:43.413630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f3de3fdbe0'
down_revision = 'be6d46598b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frequency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frequency_id'), 'frequency', ['id'], unique=False)
    op.create_table('frequencies',
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('frequencies_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['frequencies_id'], ['frequency.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frequencies')
    op.drop_index(op.f('ix_frequency_id'), table_name='frequency')
    op.drop_table('frequency')
    # ### end Alembic commands ###
