"""frequency modification

Revision ID: c86556e15778
Revises: d237a3e9e69d
Create Date: 2019-03-06 12:36:26.536010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86556e15778'
down_revision = 'd237a3e9e69d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frequencies')
    op.add_column('opportunity', sa.Column('frequency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'opportunity', 'frequency', ['frequency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunity', type_='foreignkey')
    op.drop_column('opportunity', 'frequency_id')
    op.create_table('frequencies',
    sa.Column('opportunity_id', sa.INTEGER(), nullable=True),
    sa.Column('frequencies_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['frequencies_id'], ['frequency.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], )
    )
    # ### end Alembic commands ###
