"""empty message

Revision ID: dff188188029
Revises: a260230e29cb
Create Date: 2019-04-27 22:29:41.229608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff188188029'
down_revision = 'a260230e29cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity', sa.Column('location_state', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity', 'location_state')
    # ### end Alembic commands ###
