"""agegroupinterest model and opportunity relationship

Revision ID: e2263aed3789
Revises: 558109202e0c
Create Date: 2018-10-21 16:50:31.876800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2263aed3789'
down_revision = '558109202e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_group_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_age_group_interest_id'), 'age_group_interest', ['id'], unique=False)
    op.create_table('age_group_interests',
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('age_group_interests_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['age_group_interests_id'], ['age_group_interest.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('age_group_interests')
    op.drop_index(op.f('ix_age_group_interest_id'), table_name='age_group_interest')
    op.drop_table('age_group_interest')
    # ### end Alembic commands ###
