"""empty message

Revision ID: e939106b7500
Revises: d237a3e9e69d
Create Date: 2019-03-17 16:37:46.074287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e939106b7500'
down_revision = 'd237a3e9e69d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'opportunity', 'frequency', ['frequency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity', sa.Column('tag_string', sa.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'opportunity', type_='foreignkey')
    # ### end Alembic commands ###
