"""empty message

Revision ID: fe12c2d406ef
Revises: a095c5d1eb8d
Create Date: 2019-01-03 19:48:26.400252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe12c2d406ef'
down_revision = 'a095c5d1eb8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity', sa.Column('location_city', sa.String(length=50), nullable=True))
    op.add_column('opportunity', sa.Column('location_street', sa.String(length=100), nullable=True))
    op.add_column('opportunity', sa.Column('location_zip', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity', 'location_zip')
    op.drop_column('opportunity', 'location_street')
    op.drop_column('opportunity', 'location_city')
    # ### end Alembic commands ###
